  BaseURL = "https://kevinsdunn.github.io/"
  languageCode = "en-us"
  title = "Lazy Cat Yarn"
  theme = "shadowcat"
  relativeURLS = true

  [module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"

  [caches]
  [caches.images]
    dir = ':cacheDir/images'